apiVersion: v1
data:
  postgresql.pass: MzRlOGVjOTUzNGRmZWJlZTY2MzA4ZTg1ZjU1ODUxYzc3MDI1YWM2MTI4OTc3MjVhOTFjZDNmZDZhZTA2ZGZhMg==
  postgresql.user: aWJtX2Nsb3VkX2VjMGU1NzA0X2EyZjFfNDViNV9iNjZlXzk0NGMyZDAwZDk5Yw==
kind: Secret
metadata:
  creationTimestamp: "2020-05-07T16:07:38Z"
  name: postgresql-access
  namespace: seme-lab-l1c1-quarkus-native
  resourceVersion: "13916175"
  selfLink: /api/v1/namespaces/seme-lab-l1c1-quarkus-native/secrets/postgresql-access
  uid: 51fc205b-e3de-483b-a199-cae272659ac5
type: Opaque
